### ISSUE TITLE
pypi release is broken

### ISSUE THREAD

**Issue by p-sherratt** [robotframework-thailand/robotframework-jsonlibrary#15]
robotframework-jsonlibrary release 0.2 is broken on pypi - but looks like relative imports are fixed on github master...  can you push the fix out as new release to pypi please? :-)

$ pip install robotframework-jsonlibrary
Collecting robotframework-jsonlibrary
  Using cached https://files.pythonhosted.org/packages/e0/3c/609d90b967905c0b5c90f736666531e025756e71f3d538546cabff61ef3e/robotframework-jsonlibrary-0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ct5ux1vz/robotframework-jsonlibrary/setup.py", line 5, in <module>
        from JSONLibrary.version import VERSION
      File "/tmp/pip-build-ct5ux1vz/robotframework-jsonlibrary/JSONLibrary/__init__.py", line 2, in <module>
        from JSONLibraryKeywords import JSONLibraryKeywords
    ModuleNotFoundError: No module named 'JSONLibraryKeywords'

    ----------------------------------------

**Comment by jaasal** [comment]
Meanwhile you can install directly from master: pip install https://github.com/nottyo/robotframework-jsonlibrary/archive/master.zip

**Comment by ohmrefresh** [comment]
I Found some missing  in python file init.py on https://pypi.org/project/robotframework-jsonlibrary/ and this repo. It make error at same first comment. I think need to rebuild this repo to release at pypi again.

![Screen Shot 2562-05-14 at 7 44 18 PM](https://user-images.githubusercontent.com/240996/57699134-617dbd80-7681-11e9-807f-5430dfc17627.png)

@nottyo 

Path
https://github.com/nottyo/robotframework-jsonlibrary/blob/master/JSONLibrary/__init__.py

**Comment by ohmrefresh** [comment]
@p-sherratt please update   https://pypi.org/project/robotframework-jsonlibrary/0.3/

**Comment by wichy13** [comment]
please update version to v0.3
