### ISSUE TITLE
Keywords not found by intellibot

### ISSUE THREAD

**Issue by mike-white-extr** [robotframework-thailand/robotframework-jsonlibrary#17]
Issue with Pycharm, Intellibot plugin and the keyword decorator that have single quoted keyword name.
eg.   @keyword('Add Object To Json') 
Intellibot seems to have issues with the decorators as defined in the robotframework-jsonlibrary.
It will only find single quoted keyword names, but not the unquoted keyword names when the @keyword('keyword name') is used.
At runtime robot only works with the unquoted Keywords.
If I comment out the decorators in my copy of robotframework-jsonlibrary,  IntelliBot finds the unquoted keywords fine.

PyCharm 2019.1.2 (Community Edition)
Build #PC-191.7141.48, built on May 7, 2019
JRE: 11.0.2+9-b159.56 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
IntelliBot @SeleniumLibrary Patched  v0.10.143.381
robotframework-jsonlibrary   0.3
Python  3.7.3

**Comment by wichy13** [comment]
Can you try this plugin (https://github.com/lkrazy/intellibot)?
It fix issue ("Keyword definition not found" for SeleniumLibrary in PyCharm #191" : https://github.com/millennialmedia/intellibot/issues/191).

Is it relate your issue?

**Comment by MoSedky** [comment]
You can try to change ' ' to " " and then it will be defined by Pycharm. Example:
`@keyword('Get Value From Json')` change it to `@keyword("Get Value From Json") `. It did work for me
