### ISSUE TITLE
site with keyword documentation gives 404

### ISSUE THREAD

**Issue by ppazos** [robotframework-thailand/robotframework-jsonlibrary#18]
from the link in the README.md

**Comment by Tset-Noitamotua** [comment]
keyword documentation is down

has anybody an alternative link?

**Comment by wichy13** [comment]
Can you use this?
https://robotframework-thailand.github.io/robotframework-jsonlibrary/JSONLibrary.html

It's in README.md

**Comment by Tset-Noitamotua** [comment]
the link above seems to work
