### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by php-coder** [robotframework-thailand/robotframework-jsonlibrary#24]
Could you add a license, please?

**Comment by franktuma** [comment]
Agreed. Please add a license to allow others to know how this plug-in can be used. See this guide for help: https://opensource.guide/legal/

**Comment by franktuma** [comment]
It appears this is listed as Public Domain on https://pypi.org/project/robotframework-jsonlibrary/, I'll suggest this to be added

**Comment by franktuma** [comment]
Created pull request #28 to resolve.
