### ISSUE TITLE
Cannot create response object with empty array or object in body

### ISSUE THREAD

**Issue by mwsluis** [robotframework-thailand/robotframework-jsonlibrary#27]
When I want the mockserver to respond with a body with an empty array [] or object {}, the 'body' parameter is not in the response. 

in library.py line 95 a test is done:
`if body_type is 'JSON' and body:
    rsp['body'] = json.dumps(body)`

However, when body is [] or {}, bool([]) and bool({}) evaluate to False. So the next line is skipped.
possible fix:
`if body_type is 'JSON' and body is not None:
    rsp['body'] = json.dumps(body)`

**Comment by elrandira** [comment]
hi, wrong github... ?
