### ISSUE TITLE
Keyword to write JSON object to file

### ISSUE THREAD

**Issue by theodore86** [robotframework-thailand/robotframework-jsonlibrary#29]
Hi,

Would be useful to have an keyword **Dump JSON To File** in order to serialize the object to file. Mostly in cases where we need to update an value and then write it back to file for configuration purposes.

**Comment by otemek** [comment]
Hi
Probably it's too late, but  if not then You can achieve it just by adding one keyword from **OperatingSystem** library
```
*** Settings ***
Library    JsonLibrary
Library    OperatingSystem
...
*** Test Cases ***
Save Json to File
    ${json_obj}    Load JSON From File    /path/to/file.json
    ... do whatever you have to with your json
    ${json_str}    Convert JSON To String    ${json_obj}
    Create File    path/to/You_json_file.json    ${json_str}
```
If that's not enough , then i can handle this new keyword and try to merge if author/main contributors are fine with it :)
