### ISSUE TITLE
Add Object To Json doesn't add anything unless key already in the json object

### ISSUE THREAD

**Issue by pavelsaman** [robotframework-thailand/robotframework-jsonlibrary#30]
Name of this keyword `Add Object To Json` suggests it will add something.

However, when I have e.g. an empty json object:

```
{
    
}
```

and I run:

```
*** Settings ***
Library    JSONLibrary 

*** Test Cases *** 
Empty JSON
    ${data}    Load JSON From File    empty.json
    Add Object To Json    ${data}    $..name    pavelsaman   
    Log    ${data}    
```

it will log `{ }`.

`name` has to exist in order for the keyword to do something.

It's obvious why:

```python
json_path_expr = parse(json_path)
for match in json_path_expr.find(json_object):
    if type(match.value) is dict:
        match.value.update(object_to_add)
    if type(match.value) is list:
        match.value.append(object_to_add)

return json_object
```

when the `json_object` is empty, it won't even enter the for loop.

When my initial json object is:

```
{
    "name": []
}
```

it will result in:

```
{'name': [['pavelsaman']]}
```

which is not desired. Similarly with a dict in the initial json.

It's at least a naming issue when by reading the name and documentation, I'd expect something gets added no matter what the initial state (provided I pass a valid json object to the keyword).

**Comment by elrandira** [comment]
Looking at the unitary test. Previously, The solution to your issue was to use this syntax:
```
*** Settings ***
Library    JSONLibrary 

*** Test Cases *** 
Empty JSON
    ${data}    Load JSON From File    empty.json
    ${object_to_add}=    Create Dictionary    name=pavelsaman
    ${json_obj}=    Add Object To Json     ${data}    $    ${object_to_add}
    Log    ${data}   
```

With the commit proposal I made, you can now use yours.

```
*** Settings ***
Library    JSONLibrary 

*** Test Cases *** 
Empty JSON
    ${data}    Load JSON From File    empty.json
    Add Object To Json    ${data}    $.name    pavelsaman   
    Log    ${data}  
```

Note that only one dot is typed before _name_ as we want to add it to root of _data_
