### ISSUE TITLE
Missing keywords

### ISSUE THREAD

**Issue by mgrossmann** [robotframework-thailand/robotframework-jsonlibrary#38]
Hi there,

I'm  a bit confused with the version and available keywords.
After installing latest version via pip (0.3.1) the keyword 'Should Have Value In Json' is not available to me.

Is this because this keyword is only available in a newer release?

Thank for clarification.

**Comment by elrandira** [comment]
Hi, this should be part of version 0.4 that will come soon.

The pypi version is the 0.3.1 that doesn't contain this keyword but the code on this github has it (future 0.4.0).

You can install this code with _pip install git+https://github.com/robotframework-thailand/robotframework-jsonlibrary.git_

**Comment by elrandira** [comment]
finally found out how to deliver v0.4
