### ISSUE TITLE
Request to reverse issue #5

### ISSUE THREAD

**Issue by rarevogel** [robotframework-thailand/robotframework-jsonlibrary#43]
Hi, in release 0.4 issue #5 was included. My testcases are now breaking because the keyword 'Get Value From Json' now fails when the provided element is not present in the JSON. I use this keyword to perform certain cleanup actions, and the cleanup is done in a followup loop, that loops through the resulting list from the 'Get Value From Json' keyword. If the list is empty no cleanup is needed and the loop is simply skipped automatically. In this new version however, the keyword fails and I have to code around it to skip the cleanup-step. Granted, this can be fixed on my end by some extra code like a 'Run Keyword And Ignore Error', but I think it's fundamentally wrong to let the keyword fail when the provided element is not in the JSON. It's not an error, the element is simply not there so the returned list should be empy, like it was.

So I would like to request to reverse the code-change, and maybe start a discussion about this issue. What is the general consensus about how this should work? Does anyone agree with me? Down here an example of my current code:

`    ${ids}      Get Value From Json    ${zaken}    $..id`
`    FOR    ${id}    IN    @{ids}`
`         Delete Zaak With Id ${id}`
`    END`

**Comment by elrandira** [comment]
Hi @rarevogel,
how about adding a _raise_error=True/False_ parameter to the keyword?
There is as well a new keyword _Should have value in json_ that might be useful to you here.

you have the possibility to restrict your usage to version <0.4 in a requirements.txt as well

**Comment by ktmcgrat** [comment]
Had the same issue today after picking up the most recent JSONLibrary changes.    It is a behavior change that caused problems in our code because it now fails instead of returning an empty list if no match found.  

A switch argument would be ok, with the default changed back to original behavior.  

The docs also need to be updated to reflect whatever is decided, and clarify what happens when no match.

**Comment by elrandira** [comment]
Hi @ktmcgrat & @rarevogel,

I propose a fix in the pull requests section. Please have a look if you wish, I'll deliver it at the end of the day CET.

**Comment by rarevogel** [comment]
> Hi @ktmcgrat & @rarevogel,
> 
> I propose a fix in the pull requests section. Please have a look if you wish, I'll deliver it at the end of the day.

Looks good to me, great solution, thanks for your quick reply.
