### ISSUE TITLE
JSONLibrary keywords are not working

### ISSUE THREAD

**Issue by jelikapahwa** [robotframework-thailand/robotframework-jsonlibrary#47]
Hi there,

Since yesterday, our automated test cases started failing because of latest version 0.5 and when I looked at source code, it seems keywords are removed  @keyword("Convert String To JSON") from
 @staticmethod
    def convert_json_to_string(json_object):
        """Convert JSON object to string

        Arguments:
            - json_object: json as a dictionary object.

**Comment by elrandira** [comment]
Hi Jelikapahwa,

this is very curious as the keywords were validated before being released as part of 0.5. Are you working with python3?

Could you share a log of the issue?

You can try running acceptance\JSONLibrary.robot from this repository as well. I have no issue on my side

**Comment by jelikapahwa** [comment]
yes, I'm working with python3.7. If you look at screenshot, even after running "DELETE Object from JSON" command, it didn't removed the attribute. I reverted back to 0.4.1 version, it worked fine. 
![keyword](https://user-images.githubusercontent.com/80296188/183781629-d8aec748-89ad-429d-aa43-b668fcd610e2.PNG)

**Comment by elrandira** [comment]
I know why. First of all, if you have the possibility, you should switch to python 3.8 or 3.9 as 3.7 is not tested (it could be one day).

Secondly, your implementation of JSONLibrary is wrong and you are using an issue that was solved with version 0.5.
You are supposed to assign _${jwt_data}_ to the value returned by _Delete Object From Json_.

This was the initial implementation but since Python works in this case with reference of the object, the json object passed as argument was modified directly. This is now fixed, as we are now duplicating the object and modifying its copy.

Modify your testcase to do 
```
${jwt_data}=  Delete Object From Json  ${jwt_data}  $.claim.sharing_duration
Log  ${jwt_data}
```

**Comment by iSumitBanik** [comment]
Same here, "Update Value to JSON" keyword is not working, too !

`Python Version: 3.6`
P.S: I will create a separate issue once I confirm all my details.

**Comment by elrandira** [comment]
same comment: 
- switch to higher version of python as python 3.6 reached end of life https://endoflife.date/python
- make sure when you are using keywords to modify a jsonobject that you get the modified object as the returned value. **This is the legacy behavior of this library**, as specified in the documentation anything else is a potential bug and unwanted functionality.

https://robotframework-thailand.github.io/robotframework-jsonlibrary/JSONLibrary.html#Update%20Value%20To%20Json

**Comment by iSumitBanik** [comment]
Yes, the second point helped me. 
We were missing the assignment.

Thanks @elrandira 🙏

**Comment by elrandira** [comment]
@iSumitBanik great! you are welcomed.

@jelikapahwa what about you? did you solve your issue?

**Comment by jelikapahwa** [comment]
Thanks @elrandira , it worked. I have upgraded python to 3.9 and reassigning the object back after modification.
