### ISSUE TITLE
Validate Schema: Make error messages more descriptive

### ISSUE THREAD

**Issue by Reikhard** [robotframework-thailand/robotframework-jsonlibrary#49]
When Validate Json By Schema throws a jsonschema.ValidationError it is hard to know where or what exactly the Problem is.
example:
`Json does not match the schema: {'type': 'object', 'enum': ['SUCCESS', 'ERROR', 'UNDEFINED', 'BUSINESS_ERROR']}`
there is no Info what exactly the problem is.

I would propose to change the error message from
`        except jsonschema.ValidationError as e:
            fail(f"Json does not match the schema: {e.schema}")`
to
`        except jsonschema.ValidationError as e:
            fail(f"{e.message}, Schema path: {' > '.join(e.schema_path)}")`

So the error in the example would instead read:
`'SUCCESS' is not one of ['ERROR', 'UNDEFINED', 'BUSINESS_ERROR'], Schema path: properties > state > enum`

which makes more sense to me. What do you think?

**Comment by elrandira** [comment]
That seems good. 

Please open a pull requests with your changes, don't forget to update acceptance/JSONLibrary.robot and tests/test_JSONLibrary.py if necessary.

**Comment by elrandira** [comment]
you closed your MR instead of merging it (which I think you can't do yourself). Your code is not merged into master.

**Comment by Reikhard** [comment]
oh sorry. First time contributing. I've merged with master and tried again.
