### ISSUE TITLE
Pretty print when converting json to string 

### ISSUE THREAD

**Issue by oetzus** [robotframework-thailand/robotframework-jsonlibrary#52]
When using the 'Convert Json To String' keyword, the string is not really readable for bigger jsons.
This could easily be solved by using the indent parameter in the json.dumps method:
`return json.dumps(json_object, indent=4)`

I don't know if this can cause problems for other use cases than printing a json or dumping it into a file, but if yes, the pretty printing could be done via an additional parameter for the 'Convert Json To String' keyword.

**Comment by elrandira** [comment]
yes, you can make a pull requets.

Make sure that when no parameter is provided, the output is the same as now.

from https://docs.python.org/3/library/json.html
> If indent is a non-negative integer or string, then JSON array elements and object members will be pretty-printed with that indent level. An indent level of 0, negative, or "" will only insert newlines. None (the default) selects the most compact representation. Using a positive integer indent indents that many spaces per level. If indent is a string (such as "\t"), that string is used to indent each level.
